## Test netCDF dataset processor, that opens a REF netCDF datafile to peform statsical analysis on a chosen variable. 
## Inpects the netCDF file and then adds a new statiscal output column and saves the file with a new name. 
## This is designed for testing with REF datasets that need uncertainties adding for demonstration with the REF v2.0 launch in 2026.
## Modified from a prompted python script generated by Claude AI and Paul Smith 25-11-09 
## Version 1.2 25-11-10 - amended to use only scipy library and work out standard deviation and standard error 
## This will need amending to create uncertainties such as Standard, Structured, Independent and Common Uncertainties. 

## Import necessary libraries 
import netCDF4 as nc
import numpy as np
from scipy import stats
from pathlib import Path

def inspect_netcdf(file_path):
    
    ## Inspect and display information about a NetCDF dataset.
    ## Parameters:
    ## file_path : str
        ## Path to the NetCDF file
    
    dataset = nc.Dataset(file_path, 'r')
    
    print(f"\n{'='*60}")
    print(f"NetCDF File: {file_path}")
    print(f"{'='*60}\n")
    
    print("Dimensions:")
    for dim_name, dim in dataset.dimensions.items():
        print(f"  - {dim_name}: {len(dim)}")
    
    print("\nVariables:")
    for var_name, var in dataset.variables.items():
        print(f"  - {var_name}: {var.dimensions}, shape: {var.shape}, dtype: {var.dtype}")
    
    print("\nGlobal Attributes:")
    for attr_name in dataset.ncattrs():
        print(f"  - {attr_name}: {dataset.getncattr(attr_name)}")
    
    dataset.close()
    return


def add_statistical_variable(input_file, output_file, source_variable, 
                             new_variable_name, stat_function='mean', 
                             time_axis=True):
    
    ## Add a new variable to NetCDF dataset containing statistical analysis.
    ## Parameters:
    ## input_file : str
        ## Path to input NetCDF file
    ## output_file : str
        ## Path to output NetCDF file
    ## source_variable : str
        ## Name of the variable to analyze
    ## new_variable_name : str
        ## Name for the new variable
    ## stat_function : str
        ## Statistical function to apply ('std' for standard deviation, 'sem' for standard error of mean) 
    ## time_axis : bool
        ## If True, compute statistics along time dimension

    # Open input dataset
    src_dataset = nc.Dataset(input_file, 'r')
    
    # Create output dataset
    dst_dataset = nc.Dataset(output_file, 'w', format='NETCDF4')
    
    # Copy global attributes
    dst_dataset.setncatts(src_dataset.__dict__)
    
    # Copy dimensions
    for name, dimension in src_dataset.dimensions.items():
        dst_dataset.createDimension(
            name, (len(dimension) if not dimension.isunlimited() else None)
        )
    
    # Copy all existing variables
    for name, variable in src_dataset.variables.items():
        dst_var = dst_dataset.createVariable(
            name, variable.datatype, variable.dimensions
        )
        
        # Copy variable attributes
        dst_var.setncatts(src_dataset[name].__dict__)
        
        # Copy data
        dst_var[:] = src_dataset[name][:]
    
    # Get source variable data
    source_data = src_dataset[source_variable][:]
    
    # Perform statistical analysis
    print(f"\nComputing {stat_function} of '{source_variable}'...")
    
    if time_axis and 'time' in src_dataset[source_variable].dimensions:
        # Find time dimension index
        time_dim_index = src_dataset[source_variable].dimensions.index('time')
        
        # Apply statistical function along time axis using scipy
        if stat_function == 'std':
            # Use scipy for standard deviation
            stat_data = np.std(source_data, axis=time_dim_index, ddof=1)
        elif stat_function == 'sem':
            # Use scipy for standard error of the mean
            stat_data = stats.sem(source_data, axis=time_dim_index, nan_policy='omit')
        else:
            raise ValueError(f"Unknown statistical function: {stat_function}. Use 'std' or 'sem'")
        
        # Get dimensions without time
        new_dimensions = list(src_dataset[source_variable].dimensions)
        new_dimensions.pop(time_dim_index)
        new_dimensions = tuple(new_dimensions)
        
    else:
        # Compute global statistic using scipy
        if stat_function == 'std':
            stat_data = np.std(source_data, ddof=1)
        elif stat_function == 'sem':
            stat_data = stats.sem(source_data.flatten(), nan_policy='omit')
        else:
            raise ValueError(f"Unknown statistical function: {stat_function}. Use 'std' or 'sem'")
        
        new_dimensions = ()
    
    # Create new variable
    new_var = dst_dataset.createVariable(
        new_variable_name,
        src_dataset[source_variable].datatype,
        new_dimensions
    )
    
    # Add attributes to new variable
    new_var.long_name = f"{stat_function.capitalize()} of {source_variable}"
    new_var.units = src_dataset[source_variable].units if hasattr(src_dataset[source_variable], 'units') else ''
    new_var.description = f"Statistical {stat_function} computed from {source_variable}"
    
    # Write data
    new_var[:] = stat_data
    
    print(f"New variable '{new_variable_name}' added successfully!")
    print(f"  Shape: {stat_data.shape}")
    print(f"  Data range: [{np.nanmin(stat_data):.4f}, {np.nanmax(stat_data):.4f}]")
    
    # Close datasets
    src_dataset.close()
    dst_dataset.close()
    
    print(f"\nOutput saved to: {output_file}")


def main():
    
    ## Main function - example usage with a REF dataset 
    
    # Example configuration
    input_file = "/Users/paul.smith/obs4MIPs-cmor-tables/inputs/DWD/OBS_ESACCI-CLOUD_sat_AVHRR-AMPM-fv3.0_Amon_clt_198201-201612.nc"  # Change to your input file location
    output_file = "/Users/paul.smith/obs4MIPs-cmor-tables/inputs/DWD/OBS_ESACCI-CLOUD_sat_AVHRR-AMPM-fv3.0_Amon_cltSem_198201-201612.nc"  # Change to your output file location (can be different) 
    source_variable = "clt"  # Change to your variable name 
    new_variable_name = "clt_sem"  # Your chosen name for the new variable
    stat_function = "sem"  # Options: 'std' (standard deviation), 'sem' (standard error of mean)
    
    # Check if input file exists - NOTE: CMORised datasets have long file-names 
    if not Path(input_file).exists():
        print(f"Error: Input file '{input_file}' not found!")
        print("\nPlease update the input_file variable with your NetCDF file path.")
        return
    
    # Inspect the dataset 
    print("Inspecting input dataset...")
    inspect_netcdf(input_file)
    
    # Add statistical variable that you created 
    print("\n" + "="*60)
    print("Adding new statistical variable...")
    print("="*60)
    
    add_statistical_variable(
        input_file=input_file,
        output_file=output_file,
        source_variable=source_variable,
        new_variable_name=new_variable_name,
        stat_function=stat_function,
        time_axis=True  # Set to False for global statistics
    )
    
    # Inspect the output dataset to see if the new stats variable is there. 
    print("\n" + "="*60)
    print("Inspecting output dataset...")
    print("="*60)
    inspect_netcdf(output_file)


if __name__ == "__main__":
    main()